# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170529_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='recommend_total',
            field=models.IntegerField(default=1),
        ),
    ]
