# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_add_read_at_to_add_booker'),
    ]

    operations = [
        migrations.AlterModelTable(
            'BooksAlreadyRead', 'books_booksalreadyread',
        ),
    ]
