# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_auto_20170630_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Book',
            name='data_read'

        ),

    ]
