# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_delete_dataread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_comment',
            field=models.TextField(blank=True),
        )

    ]
